apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: constrainttemplates.templates.gatekeeper.sh
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
status: null
spec:
  validation: SPEC_VALIDATION_REMOVE_PLACEHOLDER
  names:
    shortNames:
      - constraints # add shortName to CRD until https://github.com/kubernetes-sigs/kubebuilder/issues/404 is solved
