# Default values for gatekeeper-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1
image: quay.io/open-policy-agent/gatekeeper:v3.0.4-beta.2
imagePullPolicy: IfNotPresent

# whether or not to install CRDs
installCRDs: true

rbac:
  create: true
  # if rbac is false this service account is used
  serviceAccountName: default

nodeSelector: {}
tolerations: []
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 300Mi
