apiVersion: v1
entries:
  gatekeeper:
    - apiVersion: v1
      appVersion: v3.1.0
      created: "2020-08-27T09:43:27.832214979-07:00"
      description: A Helm chart for Gatekeeper
      digest: e8067f31c6bb7305a551b385078d1b760c50503929a549188563a42238abe625
      home: https://github.com/open-policy-agent/gatekeeper
      keywords:
        - open policy agent
      name: gatekeeper
      sources:
        - https://github.com/open-policy-agent/gatekeeper.git
      urls:
        - https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-v3.1.0.tgz
      version: v3.1.0
    - apiVersion: v1
      appVersion: v3.1.0-rc.1
      created: "2020-08-14T12:56:49.1898705-07:00"
      description: A Helm chart for Gatekeeper
      digest: 92d0b106768faa7d880fb772f7c6b2cba591ab348897db4317543241b32c7fb7
      home: https://github.com/open-policy-agent/gatekeeper
      keywords:
        - open policy agent
      name: gatekeeper
      sources:
        - https://github.com/open-policy-agent/gatekeeper.git
      urls:
        - https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-v3.1.0-rc.1.tgz
      version: v3.1.0-rc.1
    - apiVersion: v1
      appVersion: v3.1.0-beta.12
      created: "2020-07-30T14:33:05.2243164-07:00"
      description: A Helm chart for Gatekeeper
      digest: 8c47867d1fcfcd6d017df750ae55cdc37870bc27bb5bdbba9053d5bebc5f2c3f
      home: https://github.com/open-policy-agent/gatekeeper
      keywords:
        - open policy agent
      name: gatekeeper
      sources:
        - https://github.com/open-policy-agent/gatekeeper.git
      urls:
        - https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-v3.1.0-beta.12.tgz
      version: v3.1.0-beta.12
    - apiVersion: v1
      appVersion: v3.1.0-beta.11
      created: "2020-07-24T16:56:23.670543818-07:00"
      description: A Helm chart for Gatekeeper
      digest: 937aeddadbeac8fa1b71169c4fcde5229fa8445b0caec6339dc7cae2ac10d43f
      home: https://github.com/open-policy-agent/gatekeeper
      keywords:
        - open policy agent
      name: gatekeeper
      sources:
        - https://github.com/open-policy-agent/gatekeeper.git
      urls:
        - https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-v3.1.0-beta.11.tgz
      version: v3.1.0-beta.11
    - apiVersion: v1
      appVersion: v3.1.0-beta.10
      created: "2020-06-29T15:35:37.1773834-07:00"
      description: A Helm chart for Gatekeeper
      digest: 68559bfa5c891be94297196ff0dcb6b2aa9341d9d7b060520ea4ac88cd1cbe2b
      home: https://github.com/open-policy-agent/gatekeeper
      keywords:
        - open policy agent
      name: gatekeeper
      sources:
        - https://github.com/open-policy-agent/gatekeeper.git
      urls:
        - https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-v3.1.0-beta.10.tgz
      version: v3.1.0-beta.10
    - apiVersion: v1
      appVersion: v3.1.0-beta.9
      created: "2020-05-21T03:44:42.0381923-07:00"
      description: A Helm chart for Gatekeeper
      digest: 2f912727f0610dd367be79e4b8a7a5a208c56c84f71b9c0325a6ff0569aff7bc
      home: https://github.com/open-policy-agent/gatekeeper
      keywords:
        - open policy agent
      name: gatekeeper
      sources:
        - https://github.com/open-policy-agent/gatekeeper.git
      urls:
        - https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-v3.1.0-beta.9.tgz
      version: v3.1.0-beta.9
generated: "2020-08-28T19:08:45.020333511Z"
