{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: '{{ include "gatekeeper-operator.name" . }}'
    chart: '{{ include "gatekeeper-operator.chart" . }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: '{{ template "gatekeeper-operator.fullname" . }}binding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ template "gatekeeper-operator.fullname" . }}'
subjects:
- kind: ServiceAccount
  name: '{{ template "gatekeeper-operator.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace | quote }}'
{{- end }}
