{{- if (and .Values.installCRDs (not (.Capabilities.APIVersions.Has "templates.gatekeeper.sh/v1beta1"))) }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app: '{{ include "gatekeeper-operator.name" . }}'
    chart: '{{ include "gatekeeper-operator.chart" . }}'
    controller-tools.k8s.io: "1.0"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: constrainttemplates.templates.gatekeeper.sh
spec:
  group: templates.gatekeeper.sh
  names:
    kind: ConstraintTemplate
    plural: constrainttemplates
    shortNames:
    - constraints
  scope: Cluster
  version: v1beta1
{{- end }}
