{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gatekeeper-operator.serviceAccountName" . }}
  namespace: gatekeeper-system
  labels:
    app: {{ template "gatekeeper-operator.name" . }}
    chart: {{ template "gatekeeper-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
