apiVersion: v1
kind: Service
metadata:
  name: {{ template "gatekeeper-operator.fullname" . }}
  labels:
    app: {{ template "gatekeeper-operator.name" . }}
    chart: {{ template "gatekeeper-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "gatekeeper-operator.name" . }}
  ports:
  - port: 443
