apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gatekeeper-operator.fullname" . }}
  namespace: gatekeeper-system
  labels:
    app: {{ template "gatekeeper-operator.name" . }}
    chart: {{ template "gatekeeper-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ template "gatekeeper-operator.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "gatekeeper-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gatekeeper-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "gatekeeper-operator.serviceAccountName" . }}
      containers:
      - name: manager
        command:
        - /root/manager
        args:
          - "--auditInterval=30"
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SECRET_NAME
            value: gatekeeper-webhook-server-secret
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 443
          name: webhook-server
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
        volumeMounts:
        - mountPath: /certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: gatekeeper-webhook-server-secret
