# Default values for gatekeeper-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicas: 1
auditInterval: 60
constraintViolationsLimit: 20
image:
  repository: quay.io/open-policy-agent/gatekeeper
  release: v3.0.4-beta.2
  pullPolicy: IfNotPresent
nodeSelector: {}
tolerations: []
